# SPDX-License-Identifier: LGPL-2.1-or-later
# See Notices.txt for copyright information
sudo: required
services:
  - docker
# just need bash and docker, but use c because it's probably the simplest
language: c
script: docker build .
