# SPDX-License-Identifier: LGPL-2.1-or-later
# Copyright 2018 Jacob Lifshay
[workspace]
members = [
    "vulkan-driver",
]

[profile.dev]
panic = "unwind"

[profile.release]
panic = "abort"

[profile.bench]
panic = "abort"
