/*
 * Copyright 2017 Jacob Lifshay
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in all
 * copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 *
 */
#ifndef VULKAN_REMOVE_XLIB_MACROS_H_
#define VULKAN_REMOVE_XLIB_MACROS_H_

#ifdef VK_USE_PLATFORM_XLIB_KHR

// include Xlib to prevent later inclusions from redefining all the macros

#include <X11/Xlib.h>
#include <X11/Xlib-xcb.h>

// remove all the Xlib macros that clutter everything up; list generated by find-xlib-macros.sh

#ifdef Above
#undef Above
#endif
#ifdef AllPlanes
#undef AllPlanes
#endif
#ifdef AllTemporary
#undef AllTemporary
#endif
#ifdef AllocAll
#undef AllocAll
#endif
#ifdef AllocNone
#undef AllocNone
#endif
#ifdef AllowExposures
#undef AllowExposures
#endif
#ifdef AlreadyGrabbed
#undef AlreadyGrabbed
#endif
#ifdef Always
#undef Always
#endif
#ifdef AnyButton
#undef AnyButton
#endif
#ifdef AnyKey
#undef AnyKey
#endif
#ifdef AnyModifier
#undef AnyModifier
#endif
#ifdef AnyPropertyType
#undef AnyPropertyType
#endif
#ifdef ArcChord
#undef ArcChord
#endif
#ifdef ArcPieSlice
#undef ArcPieSlice
#endif
#ifdef AsyncBoth
#undef AsyncBoth
#endif
#ifdef AsyncKeyboard
#undef AsyncKeyboard
#endif
#ifdef AsyncPointer
#undef AsyncPointer
#endif
#ifdef AutoRepeatModeDefault
#undef AutoRepeatModeDefault
#endif
#ifdef AutoRepeatModeOff
#undef AutoRepeatModeOff
#endif
#ifdef AutoRepeatModeOn
#undef AutoRepeatModeOn
#endif
#ifdef BadAccess
#undef BadAccess
#endif
#ifdef BadAlloc
#undef BadAlloc
#endif
#ifdef BadAtom
#undef BadAtom
#endif
#ifdef BadColor
#undef BadColor
#endif
#ifdef BadCursor
#undef BadCursor
#endif
#ifdef BadDrawable
#undef BadDrawable
#endif
#ifdef BadFont
#undef BadFont
#endif
#ifdef BadGC
#undef BadGC
#endif
#ifdef BadIDChoice
#undef BadIDChoice
#endif
#ifdef BadImplementation
#undef BadImplementation
#endif
#ifdef BadLength
#undef BadLength
#endif
#ifdef BadMatch
#undef BadMatch
#endif
#ifdef BadName
#undef BadName
#endif
#ifdef BadPixmap
#undef BadPixmap
#endif
#ifdef BadRequest
#undef BadRequest
#endif
#ifdef BadValue
#undef BadValue
#endif
#ifdef BadWindow
#undef BadWindow
#endif
#ifdef Below
#undef Below
#endif
#ifdef BitmapBitOrder
#undef BitmapBitOrder
#endif
#ifdef BitmapPad
#undef BitmapPad
#endif
#ifdef BitmapUnit
#undef BitmapUnit
#endif
#ifdef BlackPixel
#undef BlackPixel
#endif
#ifdef BlackPixelOfScreen
#undef BlackPixelOfScreen
#endif
#ifdef Bool
#undef Bool
#endif
#ifdef BottomIf
#undef BottomIf
#endif
#ifdef Button1
#undef Button1
#endif
#ifdef Button1Mask
#undef Button1Mask
#endif
#ifdef Button1MotionMask
#undef Button1MotionMask
#endif
#ifdef Button2
#undef Button2
#endif
#ifdef Button2Mask
#undef Button2Mask
#endif
#ifdef Button2MotionMask
#undef Button2MotionMask
#endif
#ifdef Button3
#undef Button3
#endif
#ifdef Button3Mask
#undef Button3Mask
#endif
#ifdef Button3MotionMask
#undef Button3MotionMask
#endif
#ifdef Button4
#undef Button4
#endif
#ifdef Button4Mask
#undef Button4Mask
#endif
#ifdef Button4MotionMask
#undef Button4MotionMask
#endif
#ifdef Button5
#undef Button5
#endif
#ifdef Button5Mask
#undef Button5Mask
#endif
#ifdef Button5MotionMask
#undef Button5MotionMask
#endif
#ifdef ButtonMotionMask
#undef ButtonMotionMask
#endif
#ifdef ButtonPress
#undef ButtonPress
#endif
#ifdef ButtonPressMask
#undef ButtonPressMask
#endif
#ifdef ButtonRelease
#undef ButtonRelease
#endif
#ifdef ButtonReleaseMask
#undef ButtonReleaseMask
#endif
#ifdef CWBackPixel
#undef CWBackPixel
#endif
#ifdef CWBackPixmap
#undef CWBackPixmap
#endif
#ifdef CWBackingPixel
#undef CWBackingPixel
#endif
#ifdef CWBackingPlanes
#undef CWBackingPlanes
#endif
#ifdef CWBackingStore
#undef CWBackingStore
#endif
#ifdef CWBitGravity
#undef CWBitGravity
#endif
#ifdef CWBorderPixel
#undef CWBorderPixel
#endif
#ifdef CWBorderPixmap
#undef CWBorderPixmap
#endif
#ifdef CWBorderWidth
#undef CWBorderWidth
#endif
#ifdef CWColormap
#undef CWColormap
#endif
#ifdef CWCursor
#undef CWCursor
#endif
#ifdef CWDontPropagate
#undef CWDontPropagate
#endif
#ifdef CWEventMask
#undef CWEventMask
#endif
#ifdef CWHeight
#undef CWHeight
#endif
#ifdef CWOverrideRedirect
#undef CWOverrideRedirect
#endif
#ifdef CWSaveUnder
#undef CWSaveUnder
#endif
#ifdef CWSibling
#undef CWSibling
#endif
#ifdef CWStackMode
#undef CWStackMode
#endif
#ifdef CWWidth
#undef CWWidth
#endif
#ifdef CWWinGravity
#undef CWWinGravity
#endif
#ifdef CWX
#undef CWX
#endif
#ifdef CWY
#undef CWY
#endif
#ifdef CapButt
#undef CapButt
#endif
#ifdef CapNotLast
#undef CapNotLast
#endif
#ifdef CapProjecting
#undef CapProjecting
#endif
#ifdef CapRound
#undef CapRound
#endif
#ifdef CellsOfScreen
#undef CellsOfScreen
#endif
#ifdef CenterGravity
#undef CenterGravity
#endif
#ifdef CirculateNotify
#undef CirculateNotify
#endif
#ifdef CirculateRequest
#undef CirculateRequest
#endif
#ifdef ClientMessage
#undef ClientMessage
#endif
#ifdef ClipByChildren
#undef ClipByChildren
#endif
#ifdef ColormapChangeMask
#undef ColormapChangeMask
#endif
#ifdef ColormapInstalled
#undef ColormapInstalled
#endif
#ifdef ColormapNotify
#undef ColormapNotify
#endif
#ifdef ColormapUninstalled
#undef ColormapUninstalled
#endif
#ifdef Complex
#undef Complex
#endif
#ifdef ConfigureNotify
#undef ConfigureNotify
#endif
#ifdef ConfigureRequest
#undef ConfigureRequest
#endif
#ifdef ConnectionNumber
#undef ConnectionNumber
#endif
#ifdef ControlMapIndex
#undef ControlMapIndex
#endif
#ifdef ControlMask
#undef ControlMask
#endif
#ifdef Convex
#undef Convex
#endif
#ifdef CoordModeOrigin
#undef CoordModeOrigin
#endif
#ifdef CoordModePrevious
#undef CoordModePrevious
#endif
#ifdef CopyFromParent
#undef CopyFromParent
#endif
#ifdef CreateNotify
#undef CreateNotify
#endif
#ifdef CurrentTime
#undef CurrentTime
#endif
#ifdef CursorShape
#undef CursorShape
#endif
#ifdef DefaultBlanking
#undef DefaultBlanking
#endif
#ifdef DefaultColormap
#undef DefaultColormap
#endif
#ifdef DefaultColormapOfScreen
#undef DefaultColormapOfScreen
#endif
#ifdef DefaultDepth
#undef DefaultDepth
#endif
#ifdef DefaultDepthOfScreen
#undef DefaultDepthOfScreen
#endif
#ifdef DefaultExposures
#undef DefaultExposures
#endif
#ifdef DefaultGC
#undef DefaultGC
#endif
#ifdef DefaultGCOfScreen
#undef DefaultGCOfScreen
#endif
#ifdef DefaultRootWindow
#undef DefaultRootWindow
#endif
#ifdef DefaultScreen
#undef DefaultScreen
#endif
#ifdef DefaultScreenOfDisplay
#undef DefaultScreenOfDisplay
#endif
#ifdef DefaultVisual
#undef DefaultVisual
#endif
#ifdef DefaultVisualOfScreen
#undef DefaultVisualOfScreen
#endif
#ifdef DestroyAll
#undef DestroyAll
#endif
#ifdef DestroyNotify
#undef DestroyNotify
#endif
#ifdef DirectColor
#undef DirectColor
#endif
#ifdef DisableAccess
#undef DisableAccess
#endif
#ifdef DisableScreenInterval
#undef DisableScreenInterval
#endif
#ifdef DisableScreenSaver
#undef DisableScreenSaver
#endif
#ifdef DisplayCells
#undef DisplayCells
#endif
#ifdef DisplayHeight
#undef DisplayHeight
#endif
#ifdef DisplayHeightMM
#undef DisplayHeightMM
#endif
#ifdef DisplayOfScreen
#undef DisplayOfScreen
#endif
#ifdef DisplayPlanes
#undef DisplayPlanes
#endif
#ifdef DisplayString
#undef DisplayString
#endif
#ifdef DisplayWidth
#undef DisplayWidth
#endif
#ifdef DisplayWidthMM
#undef DisplayWidthMM
#endif
#ifdef DoBlue
#undef DoBlue
#endif
#ifdef DoGreen
#undef DoGreen
#endif
#ifdef DoRed
#undef DoRed
#endif
#ifdef DoesBackingStore
#undef DoesBackingStore
#endif
#ifdef DoesSaveUnders
#undef DoesSaveUnders
#endif
#ifdef DontAllowExposures
#undef DontAllowExposures
#endif
#ifdef DontPreferBlanking
#undef DontPreferBlanking
#endif
#ifdef EastGravity
#undef EastGravity
#endif
#ifdef EnableAccess
#undef EnableAccess
#endif
#ifdef EnterNotify
#undef EnterNotify
#endif
#ifdef EnterWindowMask
#undef EnterWindowMask
#endif
#ifdef EvenOddRule
#undef EvenOddRule
#endif
#ifdef EventMaskOfScreen
#undef EventMaskOfScreen
#endif
#ifdef Expose
#undef Expose
#endif
#ifdef ExposureMask
#undef ExposureMask
#endif
#ifdef FUNCPROTO
#undef FUNCPROTO
#endif
#ifdef False
#undef False
#endif
#ifdef FamilyChaos
#undef FamilyChaos
#endif
#ifdef FamilyDECnet
#undef FamilyDECnet
#endif
#ifdef FamilyInternet
#undef FamilyInternet
#endif
#ifdef FamilyInternet6
#undef FamilyInternet6
#endif
#ifdef FamilyServerInterpreted
#undef FamilyServerInterpreted
#endif
#ifdef FillOpaqueStippled
#undef FillOpaqueStippled
#endif
#ifdef FillSolid
#undef FillSolid
#endif
#ifdef FillStippled
#undef FillStippled
#endif
#ifdef FillTiled
#undef FillTiled
#endif
#ifdef FirstExtensionError
#undef FirstExtensionError
#endif
#ifdef FocusChangeMask
#undef FocusChangeMask
#endif
#ifdef FocusIn
#undef FocusIn
#endif
#ifdef FocusOut
#undef FocusOut
#endif
#ifdef FontChange
#undef FontChange
#endif
#ifdef FontLeftToRight
#undef FontLeftToRight
#endif
#ifdef FontRightToLeft
#undef FontRightToLeft
#endif
#ifdef ForgetGravity
#undef ForgetGravity
#endif
#ifdef GCArcMode
#undef GCArcMode
#endif
#ifdef GCBackground
#undef GCBackground
#endif
#ifdef GCCapStyle
#undef GCCapStyle
#endif
#ifdef GCClipMask
#undef GCClipMask
#endif
#ifdef GCClipXOrigin
#undef GCClipXOrigin
#endif
#ifdef GCClipYOrigin
#undef GCClipYOrigin
#endif
#ifdef GCDashList
#undef GCDashList
#endif
#ifdef GCDashOffset
#undef GCDashOffset
#endif
#ifdef GCFillRule
#undef GCFillRule
#endif
#ifdef GCFillStyle
#undef GCFillStyle
#endif
#ifdef GCFont
#undef GCFont
#endif
#ifdef GCForeground
#undef GCForeground
#endif
#ifdef GCFunction
#undef GCFunction
#endif
#ifdef GCGraphicsExposures
#undef GCGraphicsExposures
#endif
#ifdef GCJoinStyle
#undef GCJoinStyle
#endif
#ifdef GCLastBit
#undef GCLastBit
#endif
#ifdef GCLineStyle
#undef GCLineStyle
#endif
#ifdef GCLineWidth
#undef GCLineWidth
#endif
#ifdef GCPlaneMask
#undef GCPlaneMask
#endif
#ifdef GCStipple
#undef GCStipple
#endif
#ifdef GCSubwindowMode
#undef GCSubwindowMode
#endif
#ifdef GCTile
#undef GCTile
#endif
#ifdef GCTileStipXOrigin
#undef GCTileStipXOrigin
#endif
#ifdef GCTileStipYOrigin
#undef GCTileStipYOrigin
#endif
#ifdef GXand
#undef GXand
#endif
#ifdef GXandInverted
#undef GXandInverted
#endif
#ifdef GXandReverse
#undef GXandReverse
#endif
#ifdef GXclear
#undef GXclear
#endif
#ifdef GXcopy
#undef GXcopy
#endif
#ifdef GXcopyInverted
#undef GXcopyInverted
#endif
#ifdef GXequiv
#undef GXequiv
#endif
#ifdef GXinvert
#undef GXinvert
#endif
#ifdef GXnand
#undef GXnand
#endif
#ifdef GXnoop
#undef GXnoop
#endif
#ifdef GXnor
#undef GXnor
#endif
#ifdef GXor
#undef GXor
#endif
#ifdef GXorInverted
#undef GXorInverted
#endif
#ifdef GXorReverse
#undef GXorReverse
#endif
#ifdef GXset
#undef GXset
#endif
#ifdef GXxor
#undef GXxor
#endif
#ifdef GenericEvent
#undef GenericEvent
#endif
#ifdef GrabFrozen
#undef GrabFrozen
#endif
#ifdef GrabInvalidTime
#undef GrabInvalidTime
#endif
#ifdef GrabModeAsync
#undef GrabModeAsync
#endif
#ifdef GrabModeSync
#undef GrabModeSync
#endif
#ifdef GrabNotViewable
#undef GrabNotViewable
#endif
#ifdef GrabSuccess
#undef GrabSuccess
#endif
#ifdef GraphicsExpose
#undef GraphicsExpose
#endif
#ifdef GravityNotify
#undef GravityNotify
#endif
#ifdef GrayScale
#undef GrayScale
#endif
#ifdef HeightMMOfScreen
#undef HeightMMOfScreen
#endif
#ifdef HeightOfScreen
#undef HeightOfScreen
#endif
#ifdef HostDelete
#undef HostDelete
#endif
#ifdef HostInsert
#undef HostInsert
#endif
#ifdef ImageByteOrder
#undef ImageByteOrder
#endif
#ifdef IncludeInferiors
#undef IncludeInferiors
#endif
#ifdef InputFocus
#undef InputFocus
#endif
#ifdef InputOnly
#undef InputOnly
#endif
#ifdef InputOutput
#undef InputOutput
#endif
#ifdef IsUnmapped
#undef IsUnmapped
#endif
#ifdef IsUnviewable
#undef IsUnviewable
#endif
#ifdef IsViewable
#undef IsViewable
#endif
#ifdef JoinBevel
#undef JoinBevel
#endif
#ifdef JoinMiter
#undef JoinMiter
#endif
#ifdef JoinRound
#undef JoinRound
#endif
#ifdef KBAutoRepeatMode
#undef KBAutoRepeatMode
#endif
#ifdef KBBellDuration
#undef KBBellDuration
#endif
#ifdef KBBellPercent
#undef KBBellPercent
#endif
#ifdef KBBellPitch
#undef KBBellPitch
#endif
#ifdef KBKey
#undef KBKey
#endif
#ifdef KBKeyClickPercent
#undef KBKeyClickPercent
#endif
#ifdef KBLed
#undef KBLed
#endif
#ifdef KBLedMode
#undef KBLedMode
#endif
#ifdef KeyPress
#undef KeyPress
#endif
#ifdef KeyPressMask
#undef KeyPressMask
#endif
#ifdef KeyRelease
#undef KeyRelease
#endif
#ifdef KeyReleaseMask
#undef KeyReleaseMask
#endif
#ifdef KeymapNotify
#undef KeymapNotify
#endif
#ifdef KeymapStateMask
#undef KeymapStateMask
#endif
#ifdef LASTEvent
#undef LASTEvent
#endif
#ifdef LSBFirst
#undef LSBFirst
#endif
#ifdef LastExtensionError
#undef LastExtensionError
#endif
#ifdef LastKnownRequestProcessed
#undef LastKnownRequestProcessed
#endif
#ifdef LeaveNotify
#undef LeaveNotify
#endif
#ifdef LeaveWindowMask
#undef LeaveWindowMask
#endif
#ifdef LedModeOff
#undef LedModeOff
#endif
#ifdef LedModeOn
#undef LedModeOn
#endif
#ifdef LineDoubleDash
#undef LineDoubleDash
#endif
#ifdef LineOnOffDash
#undef LineOnOffDash
#endif
#ifdef LineSolid
#undef LineSolid
#endif
#ifdef LockMapIndex
#undef LockMapIndex
#endif
#ifdef LockMask
#undef LockMask
#endif
#ifdef LowerHighest
#undef LowerHighest
#endif
#ifdef MSBFirst
#undef MSBFirst
#endif
#ifdef MapNotify
#undef MapNotify
#endif
#ifdef MapRequest
#undef MapRequest
#endif
#ifdef MappingBusy
#undef MappingBusy
#endif
#ifdef MappingFailed
#undef MappingFailed
#endif
#ifdef MappingKeyboard
#undef MappingKeyboard
#endif
#ifdef MappingModifier
#undef MappingModifier
#endif
#ifdef MappingNotify
#undef MappingNotify
#endif
#ifdef MappingPointer
#undef MappingPointer
#endif
#ifdef MappingSuccess
#undef MappingSuccess
#endif
#ifdef MaxCmapsOfScreen
#undef MaxCmapsOfScreen
#endif
#ifdef MinCmapsOfScreen
#undef MinCmapsOfScreen
#endif
#ifdef Mod1MapIndex
#undef Mod1MapIndex
#endif
#ifdef Mod1Mask
#undef Mod1Mask
#endif
#ifdef Mod2MapIndex
#undef Mod2MapIndex
#endif
#ifdef Mod2Mask
#undef Mod2Mask
#endif
#ifdef Mod3MapIndex
#undef Mod3MapIndex
#endif
#ifdef Mod3Mask
#undef Mod3Mask
#endif
#ifdef Mod4MapIndex
#undef Mod4MapIndex
#endif
#ifdef Mod4Mask
#undef Mod4Mask
#endif
#ifdef Mod5MapIndex
#undef Mod5MapIndex
#endif
#ifdef Mod5Mask
#undef Mod5Mask
#endif
#ifdef MotionNotify
#undef MotionNotify
#endif
#ifdef NARROWPROTO
#undef NARROWPROTO
#endif
#ifdef NeedFunctionPrototypes
#undef NeedFunctionPrototypes
#endif
#ifdef NeedNestedPrototypes
#undef NeedNestedPrototypes
#endif
#ifdef NeedVarargsPrototypes
#undef NeedVarargsPrototypes
#endif
#ifdef NeedWidePrototypes
#undef NeedWidePrototypes
#endif
#ifdef NextRequest
#undef NextRequest
#endif
#ifdef NoEventMask
#undef NoEventMask
#endif
#ifdef NoExpose
#undef NoExpose
#endif
#ifdef NoSymbol
#undef NoSymbol
#endif
#ifdef Nonconvex
#undef Nonconvex
#endif
#ifdef None
#undef None
#endif
#ifdef NorthEastGravity
#undef NorthEastGravity
#endif
#ifdef NorthGravity
#undef NorthGravity
#endif
#ifdef NorthWestGravity
#undef NorthWestGravity
#endif
#ifdef NotUseful
#undef NotUseful
#endif
#ifdef NotifyAncestor
#undef NotifyAncestor
#endif
#ifdef NotifyDetailNone
#undef NotifyDetailNone
#endif
#ifdef NotifyGrab
#undef NotifyGrab
#endif
#ifdef NotifyHint
#undef NotifyHint
#endif
#ifdef NotifyInferior
#undef NotifyInferior
#endif
#ifdef NotifyNonlinear
#undef NotifyNonlinear
#endif
#ifdef NotifyNonlinearVirtual
#undef NotifyNonlinearVirtual
#endif
#ifdef NotifyNormal
#undef NotifyNormal
#endif
#ifdef NotifyPointer
#undef NotifyPointer
#endif
#ifdef NotifyPointerRoot
#undef NotifyPointerRoot
#endif
#ifdef NotifyUngrab
#undef NotifyUngrab
#endif
#ifdef NotifyVirtual
#undef NotifyVirtual
#endif
#ifdef NotifyWhileGrabbed
#undef NotifyWhileGrabbed
#endif
#ifdef Opposite
#undef Opposite
#endif
#ifdef OwnerGrabButtonMask
#undef OwnerGrabButtonMask
#endif
#ifdef ParentRelative
#undef ParentRelative
#endif
#ifdef PlaceOnBottom
#undef PlaceOnBottom
#endif
#ifdef PlaceOnTop
#undef PlaceOnTop
#endif
#ifdef PlanesOfScreen
#undef PlanesOfScreen
#endif
#ifdef PointerMotionHintMask
#undef PointerMotionHintMask
#endif
#ifdef PointerMotionMask
#undef PointerMotionMask
#endif
#ifdef PointerRoot
#undef PointerRoot
#endif
#ifdef PointerWindow
#undef PointerWindow
#endif
#ifdef PreferBlanking
#undef PreferBlanking
#endif
#ifdef PropModeAppend
#undef PropModeAppend
#endif
#ifdef PropModePrepend
#undef PropModePrepend
#endif
#ifdef PropModeReplace
#undef PropModeReplace
#endif
#ifdef PropertyChangeMask
#undef PropertyChangeMask
#endif
#ifdef PropertyDelete
#undef PropertyDelete
#endif
#ifdef PropertyNewValue
#undef PropertyNewValue
#endif
#ifdef PropertyNotify
#undef PropertyNotify
#endif
#ifdef ProtocolRevision
#undef ProtocolRevision
#endif
#ifdef ProtocolVersion
#undef ProtocolVersion
#endif
#ifdef PseudoColor
#undef PseudoColor
#endif
#ifdef QLength
#undef QLength
#endif
#ifdef QueuedAfterFlush
#undef QueuedAfterFlush
#endif
#ifdef QueuedAfterReading
#undef QueuedAfterReading
#endif
#ifdef QueuedAlready
#undef QueuedAlready
#endif
#ifdef RaiseLowest
#undef RaiseLowest
#endif
#ifdef ReparentNotify
#undef ReparentNotify
#endif
#ifdef ReplayKeyboard
#undef ReplayKeyboard
#endif
#ifdef ReplayPointer
#undef ReplayPointer
#endif
#ifdef ResizeRedirectMask
#undef ResizeRedirectMask
#endif
#ifdef ResizeRequest
#undef ResizeRequest
#endif
#ifdef RetainPermanent
#undef RetainPermanent
#endif
#ifdef RetainTemporary
#undef RetainTemporary
#endif
#ifdef RevertToNone
#undef RevertToNone
#endif
#ifdef RevertToParent
#undef RevertToParent
#endif
#ifdef RevertToPointerRoot
#undef RevertToPointerRoot
#endif
#ifdef RootWindow
#undef RootWindow
#endif
#ifdef RootWindowOfScreen
#undef RootWindowOfScreen
#endif
#ifdef ScreenCount
#undef ScreenCount
#endif
#ifdef ScreenOfDisplay
#undef ScreenOfDisplay
#endif
#ifdef ScreenSaverActive
#undef ScreenSaverActive
#endif
#ifdef ScreenSaverReset
#undef ScreenSaverReset
#endif
#ifdef SelectionClear
#undef SelectionClear
#endif
#ifdef SelectionNotify
#undef SelectionNotify
#endif
#ifdef SelectionRequest
#undef SelectionRequest
#endif
#ifdef ServerVendor
#undef ServerVendor
#endif
#ifdef SetModeDelete
#undef SetModeDelete
#endif
#ifdef SetModeInsert
#undef SetModeInsert
#endif
#ifdef ShiftMapIndex
#undef ShiftMapIndex
#endif
#ifdef ShiftMask
#undef ShiftMask
#endif
#ifdef SouthEastGravity
#undef SouthEastGravity
#endif
#ifdef SouthGravity
#undef SouthGravity
#endif
#ifdef SouthWestGravity
#undef SouthWestGravity
#endif
#ifdef StaticColor
#undef StaticColor
#endif
#ifdef StaticGravity
#undef StaticGravity
#endif
#ifdef StaticGray
#undef StaticGray
#endif
#ifdef Status
#undef Status
#endif
#ifdef StippleShape
#undef StippleShape
#endif
#ifdef StructureNotifyMask
#undef StructureNotifyMask
#endif
#ifdef SubstructureNotifyMask
#undef SubstructureNotifyMask
#endif
#ifdef SubstructureRedirectMask
#undef SubstructureRedirectMask
#endif
#ifdef Success
#undef Success
#endif
#ifdef SyncBoth
#undef SyncBoth
#endif
#ifdef SyncKeyboard
#undef SyncKeyboard
#endif
#ifdef SyncPointer
#undef SyncPointer
#endif
#ifdef TileShape
#undef TileShape
#endif
#ifdef TopIf
#undef TopIf
#endif
#ifdef True
#undef True
#endif
#ifdef TrueColor
#undef TrueColor
#endif
#ifdef UnmapGravity
#undef UnmapGravity
#endif
#ifdef UnmapNotify
#undef UnmapNotify
#endif
#ifdef Unsorted
#undef Unsorted
#endif
#ifdef VendorRelease
#undef VendorRelease
#endif
#ifdef VisibilityChangeMask
#undef VisibilityChangeMask
#endif
#ifdef VisibilityFullyObscured
#undef VisibilityFullyObscured
#endif
#ifdef VisibilityNotify
#undef VisibilityNotify
#endif
#ifdef VisibilityPartiallyObscured
#undef VisibilityPartiallyObscured
#endif
#ifdef VisibilityUnobscured
#undef VisibilityUnobscured
#endif
#ifdef WestGravity
#undef WestGravity
#endif
#ifdef WhenMapped
#undef WhenMapped
#endif
#ifdef WhitePixel
#undef WhitePixel
#endif
#ifdef WhitePixelOfScreen
#undef WhitePixelOfScreen
#endif
#ifdef WidthMMOfScreen
#undef WidthMMOfScreen
#endif
#ifdef WidthOfScreen
#undef WidthOfScreen
#endif
#ifdef WindingRule
#undef WindingRule
#endif
#ifdef XAllocID
#undef XAllocID
#endif
#ifdef XBufferOverflow
#undef XBufferOverflow
#endif
#ifdef XIMHighlight
#undef XIMHighlight
#endif
#ifdef XIMHotKeyStateOFF
#undef XIMHotKeyStateOFF
#endif
#ifdef XIMHotKeyStateON
#undef XIMHotKeyStateON
#endif
#ifdef XIMInitialState
#undef XIMInitialState
#endif
#ifdef XIMPreeditArea
#undef XIMPreeditArea
#endif
#ifdef XIMPreeditCallbacks
#undef XIMPreeditCallbacks
#endif
#ifdef XIMPreeditDisable
#undef XIMPreeditDisable
#endif
#ifdef XIMPreeditEnable
#undef XIMPreeditEnable
#endif
#ifdef XIMPreeditNone
#undef XIMPreeditNone
#endif
#ifdef XIMPreeditNothing
#undef XIMPreeditNothing
#endif
#ifdef XIMPreeditPosition
#undef XIMPreeditPosition
#endif
#ifdef XIMPreeditUnKnown
#undef XIMPreeditUnKnown
#endif
#ifdef XIMPreserveState
#undef XIMPreserveState
#endif
#ifdef XIMPrimary
#undef XIMPrimary
#endif
#ifdef XIMReverse
#undef XIMReverse
#endif
#ifdef XIMSecondary
#undef XIMSecondary
#endif
#ifdef XIMStatusArea
#undef XIMStatusArea
#endif
#ifdef XIMStatusCallbacks
#undef XIMStatusCallbacks
#endif
#ifdef XIMStatusNone
#undef XIMStatusNone
#endif
#ifdef XIMStatusNothing
#undef XIMStatusNothing
#endif
#ifdef XIMStringConversionBottomEdge
#undef XIMStringConversionBottomEdge
#endif
#ifdef XIMStringConversionBuffer
#undef XIMStringConversionBuffer
#endif
#ifdef XIMStringConversionChar
#undef XIMStringConversionChar
#endif
#ifdef XIMStringConversionConcealed
#undef XIMStringConversionConcealed
#endif
#ifdef XIMStringConversionLeftEdge
#undef XIMStringConversionLeftEdge
#endif
#ifdef XIMStringConversionLine
#undef XIMStringConversionLine
#endif
#ifdef XIMStringConversionRetrieval
#undef XIMStringConversionRetrieval
#endif
#ifdef XIMStringConversionRightEdge
#undef XIMStringConversionRightEdge
#endif
#ifdef XIMStringConversionSubstitution
#undef XIMStringConversionSubstitution
#endif
#ifdef XIMStringConversionTopEdge
#undef XIMStringConversionTopEdge
#endif
#ifdef XIMStringConversionWord
#undef XIMStringConversionWord
#endif
#ifdef XIMStringConversionWrapped
#undef XIMStringConversionWrapped
#endif
#ifdef XIMTertiary
#undef XIMTertiary
#endif
#ifdef XIMUnderline
#undef XIMUnderline
#endif
#ifdef XIMVisibleToBackword
#undef XIMVisibleToBackword
#endif
#ifdef XIMVisibleToCenter
#undef XIMVisibleToCenter
#endif
#ifdef XIMVisibleToForward
#undef XIMVisibleToForward
#endif
#ifdef XLookupBoth
#undef XLookupBoth
#endif
#ifdef XLookupChars
#undef XLookupChars
#endif
#ifdef XLookupKeySym
#undef XLookupKeySym
#endif
#ifdef XLookupNone
#undef XLookupNone
#endif
#ifdef XNArea
#undef XNArea
#endif
#ifdef XNAreaNeeded
#undef XNAreaNeeded
#endif
#ifdef XNBackground
#undef XNBackground
#endif
#ifdef XNBackgroundPixmap
#undef XNBackgroundPixmap
#endif
#ifdef XNBaseFontName
#undef XNBaseFontName
#endif
#ifdef XNClientWindow
#undef XNClientWindow
#endif
#ifdef XNColormap
#undef XNColormap
#endif
#ifdef XNContextualDrawing
#undef XNContextualDrawing
#endif
#ifdef XNCursor
#undef XNCursor
#endif
#ifdef XNDefaultString
#undef XNDefaultString
#endif
#ifdef XNDestroyCallback
#undef XNDestroyCallback
#endif
#ifdef XNDirectionalDependentDrawing
#undef XNDirectionalDependentDrawing
#endif
#ifdef XNFilterEvents
#undef XNFilterEvents
#endif
#ifdef XNFocusWindow
#undef XNFocusWindow
#endif
#ifdef XNFontInfo
#undef XNFontInfo
#endif
#ifdef XNFontSet
#undef XNFontSet
#endif
#ifdef XNForeground
#undef XNForeground
#endif
#ifdef XNGeometryCallback
#undef XNGeometryCallback
#endif
#ifdef XNHotKey
#undef XNHotKey
#endif
#ifdef XNHotKeyState
#undef XNHotKeyState
#endif
#ifdef XNInputStyle
#undef XNInputStyle
#endif
#ifdef XNLineSpace
#undef XNLineSpace
#endif
#ifdef XNMissingCharSet
#undef XNMissingCharSet
#endif
#ifdef XNOMAutomatic
#undef XNOMAutomatic
#endif
#ifdef XNOrientation
#undef XNOrientation
#endif
#ifdef XNPreeditAttributes
#undef XNPreeditAttributes
#endif
#ifdef XNPreeditCaretCallback
#undef XNPreeditCaretCallback
#endif
#ifdef XNPreeditDoneCallback
#undef XNPreeditDoneCallback
#endif
#ifdef XNPreeditDrawCallback
#undef XNPreeditDrawCallback
#endif
#ifdef XNPreeditStartCallback
#undef XNPreeditStartCallback
#endif
#ifdef XNPreeditState
#undef XNPreeditState
#endif
#ifdef XNPreeditStateNotifyCallback
#undef XNPreeditStateNotifyCallback
#endif
#ifdef XNQueryICValuesList
#undef XNQueryICValuesList
#endif
#ifdef XNQueryIMValuesList
#undef XNQueryIMValuesList
#endif
#ifdef XNQueryInputStyle
#undef XNQueryInputStyle
#endif
#ifdef XNQueryOrientation
#undef XNQueryOrientation
#endif
#ifdef XNR6PreeditCallback
#undef XNR6PreeditCallback
#endif
#ifdef XNRequiredCharSet
#undef XNRequiredCharSet
#endif
#ifdef XNResetState
#undef XNResetState
#endif
#ifdef XNResourceClass
#undef XNResourceClass
#endif
#ifdef XNResourceName
#undef XNResourceName
#endif
#ifdef XNSeparatorofNestedList
#undef XNSeparatorofNestedList
#endif
#ifdef XNSpotLocation
#undef XNSpotLocation
#endif
#ifdef XNStatusAttributes
#undef XNStatusAttributes
#endif
#ifdef XNStatusDoneCallback
#undef XNStatusDoneCallback
#endif
#ifdef XNStatusDrawCallback
#undef XNStatusDrawCallback
#endif
#ifdef XNStatusStartCallback
#undef XNStatusStartCallback
#endif
#ifdef XNStdColormap
#undef XNStdColormap
#endif
#ifdef XNStringConversion
#undef XNStringConversion
#endif
#ifdef XNStringConversionCallback
#undef XNStringConversionCallback
#endif
#ifdef XNVaNestedList
#undef XNVaNestedList
#endif
#ifdef XNVisiblePosition
#undef XNVisiblePosition
#endif
#ifdef XYBitmap
#undef XYBitmap
#endif
#ifdef XYPixmap
#undef XYPixmap
#endif
#ifdef X_HAVE_UTF8_STRING
#undef X_HAVE_UTF8_STRING
#endif
#ifdef X_PROTOCOL
#undef X_PROTOCOL
#endif
#ifdef X_PROTOCOL_REVISION
#undef X_PROTOCOL_REVISION
#endif
#ifdef XlibSpecificationRelease
#undef XlibSpecificationRelease
#endif
#ifdef YSorted
#undef YSorted
#endif
#ifdef YXBanded
#undef YXBanded
#endif
#ifdef YXSorted
#undef YXSorted
#endif
#ifdef ZPixmap
#undef ZPixmap
#endif

#endif // VK_USE_PLATFORM_XLIB_KHR

#endif // VULKAN_REMOVE_XLIB_MACROS_H_
